stages:
  data_ingestion:
    cmd: python -m src.component.data_ingestion
    deps:
      - src/component/data_ingestion.py
    outs:
      - artifacts/data_ingestion_data

  data_preprocessing:
    cmd: python -m src.component.data_preprocessing
    deps:
      - artifacts/data_ingestion_data
      - src/component/data_preprocessing.py
    outs:
      - artifacts/data_preprocessing_data

  feature_engineering:
    cmd: python -m src.component.feature_engineering
    deps:
      - artifacts/data_preprocessing_data
      - src/component/feature_engineering.py
    outs:
      - artifacts/feature_engineering_data

  model_building:
    cmd: python -m src.component.model_building
    deps:
      - artifacts/feature_engineering_data
      - src/component/model_building.py
    outs:
      - Final_model/model.pkl

  model_evaluation:
    cmd: python -m src.component.model_evaluation
    deps:
      - Final_model/model.pkl
      - src/component/model_evaluation.py
    outs:
      - reports/report.json